In [945]:
import numpy as np

In [946]:
class Board():
    def __init__(self, matrix):
        self.matrix = matrix
        self.bingo = False
    
    def mark_number(self, draw:int):
        row, col = np.where(self.matrix==draw)
        if len(row):
            self.matrix[row[0], col[0]]=-1
            if sum(self.matrix[row[0],:])==-5:
                self.bingo = True
            elif sum(self.matrix[:,col[0]])==-5:
                self.bingo = True

    def score(self):
        return sum(np.where(self.matrix==-1, 0, self.matrix))

# -----------

class Game():
    def __init__(self, file): # functions here are only called once on instanciation
        self.file = file
        self.winner = None
        self.score = None
        self.draw = None
        self.boards = self.create_boards()

    @property
    def data(self):
        with open(self.file) as f:
            return f.read().split("\n\n")

    @property
    def draws(self) -> list:
        return list(map(int, self.data[0].split(",")))
    
    def create_boards(self) -> np.array:
        boards = []
        for b in self.data[1:]:
            board = []
            for l in b.splitlines():
                board.append(list(map(int, l.split())))
            boards.append(Board(np.array(board)))
        return boards

    def play(self):
        for draw in self.draws:
            print(draw)
            for board in self.boards: # every time I call boards I calculate it again
                board.mark_number(draw)
                print(board.matrix)
                if board.bingo:
                    self.winner = board
                    self.score = 
                    self.draw = draw

                    return board.matrix, board.score()
                print(board.matrix)

    @property
    def score(self):
        return sum(np.where(self.matrix==-1, 0, self.matrix))


In [947]:
game = Game("input.txt")
game_test = Game("input_test.txt")

In [948]:
game_test.boards[0].matrix

array([[22, 13, 17, 11,  0],
       [ 8,  2, 23,  4, 24],
       [21,  9, 14, 16,  7],
       [ 6, 10,  3, 18,  5],
       [ 1, 12, 20, 15, 19]])

In [949]:
game_test.play()

7
[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16 -1]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16 -1]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8 -1 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8 -1 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3 -1]]
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3 -1]]
4
[[22 13 17 11  0]
 [ 8  2 23 -1 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[22 13 17 11  0]
 [ 8  2 23 -1 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24 -1]
 [14 21 16 12  6]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24 -1]
 [14 21 16 12  6]]
[[14 21 17 24 -1]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3 

In [ ]:
if __name__ == "__main__":
    game_test = Game("input_test.txt")
    game_test.play()
    # assert game_test.score = 4512
    game = Game(data)
    game.play()
    print(game.score)